// swift-tools-version: 6.2
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import PackageDescription

let package = Package(
  name: "GoogleCloudRecommenderLoggingV1",
  platforms: [.macOS(.v15)],
  products: [
    .library(name: "GoogleCloudRecommenderLoggingV1", targets: ["GoogleCloudRecommenderLoggingV1"])
  ],
  dependencies: [
    localOrRemotePackage(
      url: "https://github.com/googleapis/swift-google-cloud-recommender-v1",
      path: "generated/swift-google-cloud-recommender-v1",
      from: "0.3.0"
    ),
    localOrRemotePackage(
      url: "https://github.com/googleapis/swift-google-wkt",
      path: "pkgs/swift-google-wkt",
      from: "0.3.0"
    ),
  ],
  targets: [
    .target(
      name: "GoogleCloudRecommenderLoggingV1",
      dependencies: [
        .product(name: "GoogleCloudRecommenderV1", package: "swift-google-cloud-recommender-v1"),
        .product(name: "GoogleWKT", package: "swift-google-wkt"),
      ],
      swiftSettings: [
        .enableUpcomingFeature("InternalImportsByDefault"),
        .strictMemorySafety(),
      ]
    )
  ]
)

func localOrRemotePackage(url: String, path: String, from version: Version) -> Package.Dependency {
  if let env = Context.environment["GOOGLE_CLOUD_SWIFT_LOCAL_DEPS"], !env.isEmpty {
    let root = (env == "1" || env == "true") ? "\(Context.packageDirectory)/../.." : env
    return .package(path: "\(root)/\(path)")
  }
  return .package(url: url, from: version)
}
