// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleCloudRecommenderV1
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Log content of an action on a recommendation. This includes Mark* actions.
public struct ActionLog: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. User that executed this action. Eg, foo@gmail.com
  public var actor: Swift.String = Swift.String()

  /// Required. State change that was made by the actor. Eg, SUCCEEDED.
  public var state: GoogleCloudRecommenderV1.RecommendationStateInfo.State =
    GoogleCloudRecommenderV1.RecommendationStateInfo.State()

  /// Optional. Metadata that was included with the action that was taken.
  public var stateMetadata: [Swift.String: Swift.String] = [:]

  /// Required. Name of the recommendation which was acted on. Eg, :
  /// 'projects/123/locations/global/recommenders/roleReco/recommendations/r1'
  public var recommendationName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ActionLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ActionLog().with { $0.actor = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let actor = CodingKeys(stringValue: "actor")
    static let state = CodingKeys(stringValue: "state")
    static let stateMetadata = CodingKeys(stringValue: "stateMetadata")
    static let recommendationName = CodingKeys(stringValue: "recommendationName")

    static let _knownKeys: Set<Swift.String> = [
      "actor",
      "state",
      "stateMetadata",
      "recommendationName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .actor) {
      self.actor = value
    }
    if let value = try container.decodeIfPresent(
      GoogleCloudRecommenderV1.RecommendationStateInfo.State.self, forKey: .state)
    {
      self.state = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .stateMetadata)
    {
      self.stateMetadata = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recommendationName) {
      self.recommendationName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.actor, forKey: .actor)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateMetadata, forKey: .stateMetadata)
    try container.encode(self.recommendationName, forKey: .recommendationName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.logging.v1.ActionLog"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
